### ISSUE TITLE
[TODO list] Tournaments

### ISSUE THREAD

**Issue by Kotoki1337** [osu-translate-zh/osu-wiki#93]
容易忘事 给自己写了个TODO list，感觉丢组织这边比较好。想接也可以接，东西挺多的。

***

Official Tournaments:
- [ ] OWC
  - [x] 1
  - [ ] 2
  - [ ] 3
  - [ ] 2013
  - [ ] 2014
  - [ ] 2015
  - [ ] 2016
  - [ ] 2017
  - [ ] 2018
  - [ ] 2019
  - [x] 2020
- [ ] CWC
  - [ ] 1
  - [ ] 2013
  - [ ] 2014
  - [ ] 2015
  - [ ] 2016
  - [ ] 2017
  - [ ] 2018
  - [ ] 2019
  - [x] 2020 [#4626](https://github.com/ppy/osu-wiki/pull/4626)
  - [ ] 2021 (on going)
- [ ] TWC
  - [ ] 3
  - [ ] 2013
  - [ ] 2014
  - [ ] 2015
  - [ ] 2016
  - [ ] 2017
  - [ ] 2018
  - [ ] 2019
  - [ ] 2020
  - [ ] 2021 (waiting EN up-to-date)
- [ ] MWC
  - [ ] 2015
  - [ ] 2016_4K
  - [ ] 2016_7K
  - [ ] 2017_4K
  - [ ] 2017_7K
  - [ ] 2018_4K
  - [ ] 2018_7K
  - [ ] 2019_4K
  - [ ] 2019_7K
  - [x] 2020_4K [#4238](https://github.com/ppy/osu-wiki/pull/4238)

Other:

***
